[build-system]
requires = ["uv_build>=0.8.22,<0.9.0"]
build-backend = "uv_build"

[project]
name = "vandc"
version = "0.1.2"
description = "Wandb but without any features"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "human-id>=0.2.0",
    "loguru>=0.7",
    "numpy",
    "pandas",
    "pyperclip>=1.11.0",
    "qqdm>=0.0.7",
    "questionary>=2.1.0",
    "torch",
]
authors = [{ name = "Christopher Gadzinski", email = "me@cgad.ski" }]

[project.optional-dependencies]
demo = [
    "seaborn>=0.13.2",
]

[project.scripts]
vandc = "vandc.cli:main"

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.uv.build-backend]
module-name = "vandc"
module-root = ""
source-exclude = [".envrc"]
